### ISSUE TITLE
Unable to load 7z.dll 

### ISSUE THREAD

**Issue by tHeBeStXu** [Zalafina/Q7Zip#3]
Hello, I've tried to start the program. The compiling process is worked, but when I start the built program, it shows that the 7z.dll load failure!!!
Mine: vs2015 x64 , Qt creator:4.15.0, win10 x64

**Comment by tHeBeStXu** [comment]
**SOLVED**  I have installed 7zip.exe x64 for windows and copy the 7z.dll from the app folder to the solution folder. 7z.dll load failure disappear

**Comment by Zalafina** [comment]
First time I build it with Qt5 + MSVC2015 x86(32bit), so the 7z.dll is a x86(32bit) version.
I have update the pro file and 7z.dll to work with both MSVC x64(64bit) & x86(32bit) .
