### ISSUE TITLE
编译显示缺少OleAut32.lib和User32.Lib

### ISSUE THREAD

**Issue by 547951807** [Zalafina/Q7Zip#5]
g++: error: OleAut32.lib: No such file or directory
g++: error: User32.Lib: No such file or directory

**Comment by Zalafina** [comment]
Windows下MSVC编译的，请使用MSVC编译器，不要用g++，Qt 5.12.10版本测试编译和运行正常。

**Comment by 547951807** [comment]
我用的qt.5.14.2,打开工程文件之后，工程配置里面MSVC选项是灰色不可选，是缺少MSVC编译器吗

**Comment by Zalafina** [comment]
需要安装MSVC 2019的编译器，请参考网上Qt5 + MSVC开发环境搭建的方法。
